<?php
    //数据库的地址
    define("DB_ADDRESS","localhost");
    //数据库用户名
    define("ACCOUNT_NAME","root");
    //数据库用户名对应的密码
    define("PASSWORD","123456");
    //数据库的名字
    define("DB_NAME","test");
    //数据库表的名字
    define("TABLE_NAME","message");
    //数据库字段的名字
    define("FIELD_NAME","text");
?>
